name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  windows-release-build:
    name: Windows Latest Build
    permissions:
      contents: write
    runs-on: windows-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      new_version: ${{ steps.change_version.outputs.new_version }}
      changelog: ${{ steps.git-cliff2.outputs.content }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: "fast"

      - name: Pull changes
        run: git pull

      - name: Clone `CSharp-Workflow-Scripts` Python script
        run: git clone https://github.com/T2PeNBiX99wcoxKv3A4g/CSharp-Workflow-Scripts.git .scripts

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.14'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r .scripts/requirements.txt

      - name: Change version in `Main.cs`
        id: change_version
        run: python .scripts/change_version.py change-version ./Main.cs Version ${{ steps.tag_version.outputs.new_tag }}

      - name: Get version from `BepinEx-Utils`
        id: get_version
        run: python .scripts/get_version.py https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/BepinEx-Utils/refs/heads/master/.version

      - name: Change version in `thunderstore.toml`
        run: python .scripts/change_version.py change-version ./.packaging/thunderstore.toml ykysnk-BepinExUtils ${{ steps.get_version.outputs.get_version }} --only-replace

      - name: Remove all python scripts
        run: Remove-Item -Force -Recurse .scripts

      - name: Install `typos-cli` from `crates.io`
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typos-cli

      - name: Pull changes
        run: git pull

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --verbose --config-url https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/Git-Cliff-Template/refs/heads/master/cliff.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Set git user
        uses: fregante/setup-git-user@v2

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: "git commit -m 'Action: Update version in `Main.cs` and update `CHANGELOG.md`'"

      - name: Fetch from master
        run: git fetch origin master

      - name: Push code to master
        run: git push origin master

      - name: Build Executable
        run: dotnet build --configuration Release

      - name: Pull changes
        run: git pull

      - name: Generate a release body
        uses: orhun/git-cliff-action@v4
        id: git-cliff2
        with:
          args: --verbose --latest --strip header --config-url https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/Git-Cliff-Template/refs/heads/master/cliff.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: bin/Release/net48/HKSS.ShowHitbox.dll
  
  upload:
    name: Create Release
    permissions:
      contents: write
    needs: [ windows-release-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
          path: release
          merge-multiple: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.windows-release-build.outputs.new_tag }}
          name: Release ${{ needs.windows-release-build.outputs.new_tag }}
          body: ${{ needs.windows-release-build.outputs.changelog }}
  
  publish:
    name: Publish to Thunderstore
    needs: [ windows-release-build ]
    runs-on: ubuntu-latest
    environment: Thunderstore
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0'

      - name: Install `tcli`
        run: dotnet tool install -g tcli

      - name: Pull changes
        run: git pull

      - name: Copy files to `.packaging`
        run: |
          mkdir -p .packaging/dist
          cp README.md .packaging/README.md
          cp icon.png .packaging/icon.png
          cp CHANGELOG.md .packaging/dist/CHANGELOG.md
          cp LICENSE .packaging/dist/LICENSE

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: release-windows
          path: .packaging/dist

      - name: List all files
        run: |
          ls -r .packaging/
          ls -r .packaging/dist

      - name: Build Package
        run: |
          cd .packaging
          tcli publish --token ${{ secrets.THUNDERSTORE_TOKEN }} --package-version ${{ needs.windows-release-build.outputs.new_version }}